#:schema https://www.unpkg.com/wrangler/config-schema.json

compatibility_date = "2025-10-11"
name = "zashboard"
send_metrics = false

[assets]
directory = "./dist"

[observability]
enabled = true

[placement]
mode = "smart"
