name: Custom / Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Install mise
        uses: jdx/mise-action@3c2e0cf82a5b2e5249f0d3635a4d83d0ae861518 # v4
      - name: Build
        run: mise run build
      - if: github.ref == 'refs/heads/main'
        name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4
        with:
          folder: dist
          single-commit: true
