name: Custom / Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Install mise
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4
      - name: Build
        run: mise run build
      - if: github.ref == 'refs/heads/main'
        name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4
        with:
          folder: dist
          single-commit: true
